version: "3.7"
services:
    db:
        image: postgres:alpine
        environment: 
            - POSTGRESS_PASSWORD=postgres
            - POSTGRESS_USERNAME=postgres
            - POSTGRES_DB=zelda_cookbook
        volumes: 
            - sql:/var/lib/postgresql/data
        
    backend:
        build: ./zelda-cookbook-backend
        depends_on: 
            - db
    frontend:
        build: ./zelda-cookbook-frontend
        ports:
            - "80:80"
            - "8000:8000"
        depends_on: 
            - backend
volumes: 
    sql: